using Godot.Collections;

namespace GdCore.Engine_Extensions;

/// <summary>
/// Contains the results of a raycast generated by GameWorldUtils.ConstructRaycastHit3D()
/// </summary>
public class RayCastHit3D
{
    // Note: Member names match the dictionary counterparts. DON'T CHANGE THEM!
    public Vector3 position = Vector3.Inf;          // point in world space for collision
    public Vector3 normal = Vector3.Inf;            // normal in world space for collision
    public GodotObject? collider;           // 
    public int collider_id;           // Object it collided against
    public Rid rid;                   // RID it collide against
    public int shape;                 // shape index of collider
    public Variant metadata;   // metadata of collider
    public bool DidCollide;

    public RayCastHit3D()
    {
        DidCollide = false;
    }

    public RayCastHit3D(Dictionary? rayCastDict)
    {
        position = Vector3.Inf;
        DidCollide = false;

        // We return on a count of less than 6 because metadata is not always present
        if (rayCastDict == null || rayCastDict.Count < 6)
            return;

        if (rayCastDict.ContainsKey("position"))
        {
            position = (Vector3)rayCastDict["position"];
            DidCollide = true;
        }
        else
        {
            position = Vector3.Inf; // Standard practice for unknown Vector3 values
        }

        if (rayCastDict.ContainsKey("normal"))
            normal = (Vector3)rayCastDict["normal"];

        if (rayCastDict.ContainsKey("collider"))
            collider = rayCastDict["collider"].As<GodotObject>();

        if (rayCastDict.ContainsKey("collider_id"))
            collider_id = (int)rayCastDict["collider_id"];

        if (rayCastDict.ContainsKey("rid"))
            rid = (Rid)rayCastDict["rid"];

        if (rayCastDict.ContainsKey("shape"))
            shape = (int)rayCastDict["shape"];

        if (rayCastDict.ContainsKey("metadata"))
            metadata = (Variant)rayCastDict["metadata"];
    }
}